name = "qob6"
type = "webpack"
workers_dev = true
compatibility_date = "2021-12-31"

[vars]
B=''
X=''
R=''
O=''
U=''
C=''
TOKEN="1750259556:AAEEDprZUtW_dcJiX3wtmCFSVJqsv4ZE2E4"
CF_STORAGE_AREA__DEFAULT_KV_NAMESPACE = "V"

[[kv-namespaces]]
binding="V"
id="1358f8997f45407fabeb40ccc21f1fcd"


